# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sr_service/proto/sr2_0/localpose/LocalPose.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sr_service.proto.sr2_0 import base_struct_pb2 as sr__service_dot_proto_dot_sr2__0_dot_base__struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0sr_service/proto/sr2_0/localpose/LocalPose.proto\x12\x12xpilot.sr2_0.proto\x1a(sr_service/proto/sr2_0/base_struct.proto\"\xc2\x01\n\x0eGlobalPoseInfo\x12\x12\n\ntime_stamp\x18\x01 \x01(\x04\x12+\n\nworld_pose\x18\x02 \x01(\x0b\x32\x17.xpilot.sr2_0.proto.Wgs\x12\x35\n\x0forientation_cov\x18\x03 \x01(\x0b\x32\x1c.xpilot.sr2_0.proto.Vector6d\x12\r\n\x05speed\x18\x04 \x01(\x04\x12\x11\n\tspeed_cov\x18\x05 \x01(\x04\x12\x16\n\x0eloc_acc_status\x18\x06 \x01(\r\"F\n\x10LocalPoseCovInfo\x12\x32\n\x0cposition_cov\x18\x01 \x01(\x0b\x32\x1c.xpilot.sr2_0.proto.Vector6d\"\x9d\x01\n\x10LocalPoseInfoMsg\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x37\n\x0bglobal_pose\x18\x02 \x01(\x0b\x32\".xpilot.sr2_0.proto.GlobalPoseInfo\x12=\n\x0fsmooth_pose_cov\x18\x03 \x01(\x0b\x32$.xpilot.sr2_0.proto.LocalPoseCovInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sr_service.proto.sr2_0.localpose.LocalPose_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GLOBALPOSEINFO']._serialized_start=115
  _globals['_GLOBALPOSEINFO']._serialized_end=309
  _globals['_LOCALPOSECOVINFO']._serialized_start=311
  _globals['_LOCALPOSECOVINFO']._serialized_end=381
  _globals['_LOCALPOSEINFOMSG']._serialized_start=384
  _globals['_LOCALPOSEINFOMSG']._serialized_end=541
# @@protoc_insertion_point(module_scope)
