# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mf_localpose/MfLocalPose.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_struct_pb2 as base__struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emf_localpose/MfLocalPose.proto\x1a\x11\x62\x61se_struct.proto\"\xed\x01\n\x0eMfLocalPoseMsg\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12%\n\rmf_local_pose\x18\x02 \x01(\x0b\x32\x0e.LocalPoseInfo\x12*\n\x17local_frame_ref_in_ecef\x18\x03 \x01(\x0b\x32\t.Pose6DOF\x12\x14\n\x0clast_mf_time\x18\x04 \x01(\x04\x12\x15\n\rfusion_status\x18\x05 \x01(\r\x12#\n\x0bmf_dop_pose\x18\x06 \x01(\x0b\x32\x0e.LocalPoseInfo\x12#\n\x0bmf_dom_pose\x18\x07 \x01(\x0b\x32\x0e.LocalPoseInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mf_localpose.MfLocalPose_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MFLOCALPOSEMSG']._serialized_start=54
  _globals['_MFLOCALPOSEMSG']._serialized_end=291
# @@protoc_insertion_point(module_scope)
