# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sd_overall.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sensor_fusion import sensor_fusion_pb2 as sensor__fusion_dot_sensor__fusion__pb2
from online_map_fusion import online_local_map_fusion_pb2 as online__map__fusion_dot_online__local__map__fusion__pb2
from localpose import LocalPose_pb2 as localpose_dot_LocalPose__pb2
from mf_localpose import MfLocalPose_pb2 as mf__localpose_dot_MfLocalPose__pb2
from bp_hmi_output import bp_hmi_output_pb2 as bp__hmi__output_dot_bp__hmi__output__pb2
from mp_output import mp_output_pb2 as mp__output_dot_mp__output__pb2
from map_fusion import mf_lanes_for_scu_pb2 as map__fusion_dot_mf__lanes__for__scu__pb2
from state_manage import state_manage_pb2 as state__manage_dot_state__manage__pb2
from aeb_debug import aeb_debug_pb2 as aeb__debug_dot_aeb__debug__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10sd_overall.proto\x1a!sensor_fusion/sensor_fusion.proto\x1a/online_map_fusion/online_local_map_fusion.proto\x1a\x19localpose/LocalPose.proto\x1a\x1emf_localpose/MfLocalPose.proto\x1a!bp_hmi_output/bp_hmi_output.proto\x1a\x19mp_output/mp_output.proto\x1a!map_fusion/mf_lanes_for_scu.proto\x1a\x1fstate_manage/state_manage.proto\x1a\x19\x61\x65\x62_debug/aeb_debug.proto\"\x95\x03\n\x0cSDOverallMsg\x12(\n\x10sfbp_rwm_dds_msg\x18\x01 \x01(\x0b\x32\x0e.SfbpRwmDdsMsg\x12\x30\n\x14online_local_map_msg\x18\x02 \x01(\x0b\x32\x12.OnlineLocalMapMsg\x12)\n\x10mf_localpose_msg\x18\x03 \x01(\x0b\x32\x0f.MfLocalPoseMsg\x12(\n\rlocalpose_msg\x18\x04 \x01(\x0b\x32\x11.LocalPoseInfoMsg\x12*\n\x11\x62p_hmi_output_msg\x18\x05 \x01(\x0b\x32\x0f.BPHMIOutputMsg\x12#\n\rmp_output_msg\x18\x06 \x01(\x0b\x32\x0c.MpOutputMsg\x12\x36\n\x14mf_lanes_for_scu_msg\x18\x07 \x01(\x0b\x32\x18.MapFusionLanesForScuMsg\x12#\n\x06sm_msg\x18\x08 \x01(\x0b\x32\x13.StateManagementMsg\x12&\n\x07\x61\x65\x62_msg\x18\t \x01(\x0b\x32\x15.ActiveSafetyDebugMsgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sd_overall_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SDOVERALLMSG']._serialized_start=321
  _globals['_SDOVERALLMSG']._serialized_end=726
# @@protoc_insertion_point(module_scope)
