# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sr_service/proto/sr2_0/bp_hmi_output/bp_hmi_output.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sr_service.proto.sr2_0 import base_struct_pb2 as sr__service_dot_proto_dot_sr2__0_dot_base__struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8sr_service/proto/sr2_0/bp_hmi_output/bp_hmi_output.proto\x12\x12xpilot.sr2_0.proto\x1a(sr_service/proto/sr2_0/base_struct.proto\"\x8a\x06\n\x0e\x42PHMIOutputMsg\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x11\n\temergency\x18\x02 \x01(\x05\x12\x11\n\tbp_to_sm6\x18\x03 \x01(\x05\x12\x12\n\nbp_to_sm10\x18\x04 \x01(\x05\x12\x12\n\nbp_to_sm12\x18\x05 \x01(\x05\x12\x12\n\nbp_to_sm14\x18\x06 \x01(\x05\x12\x12\n\nbp_to_sm15\x18\x07 \x01(\x05\x12\x12\n\nbp_to_sm16\x18\x08 \x01(\x05\x12\x12\n\nbp_to_sm19\x18\t \x01(\x05\x12\x12\n\nbp_to_sm20\x18\n \x01(\x05\x12\x12\n\nbp_to_sm22\x18\x0b \x01(\x05\x12\x12\n\nbp_to_sm23\x18\x0c \x01(\x05\x12\x12\n\nbp_to_sm24\x18\r \x01(\x05\x12\x12\n\nbp_to_sm25\x18\x0e \x01(\x05\x12\x12\n\nbp_to_sm36\x18\x0f \x01(\x05\x12\x12\n\nbp_to_sm37\x18\x10 \x01(\x05\x12\x12\n\nbp_to_sm38\x18\x11 \x01(\x05\x12\x12\n\nbp_to_sm43\x18\x12 \x01(\x05\x12\x1a\n\x12lane_change_status\x18\x13 \x01(\x05\x12\x18\n\x10state_rd_alcctrl\x18\x14 \x01(\x05\x12\x11\n\tbp_status\x18\x15 \x01(\x05\x12\x34\n\x08\x62oudarys\x18\x16 \x03(\x0b\x32\".xpilot.sr2_0.proto.BoundaryObject\x12\x1f\n\x17surrounding_vehicles_id\x18\x17 \x03(\x05\x12*\n\"object_id_in_lane_farther_from_ego\x18\x18 \x03(\x05\x12\'\n\x1fobject_id_rear_and_close_to_ego\x18\x19 \x03(\x05\x12\x12\n\nbp_to_sm11\x18\x1a \x01(\x05\x12\x12\n\nbp_to_sm13\x18\x1b \x01(\x05\x12\x12\n\nbp_to_sm28\x18\x1c \x01(\x05\x12\x12\n\nbp_to_sm53\x18\x1d \x01(\x05\x12\x12\n\nbp_to_sm55\x18\x1e \x01(\x05\x12\x12\n\nbp_to_sm46\x18\x1f \x01(\x05\x12\x12\n\nbp_to_sm47\x18  \x01(\x05\x12\x12\n\nbp_to_sm57\x18! \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sr_service.proto.sr2_0.bp_hmi_output.bp_hmi_output_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BPHMIOUTPUTMSG']._serialized_start=123
  _globals['_BPHMIOUTPUTMSG']._serialized_end=901
# @@protoc_insertion_point(module_scope)
