# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: localpose/LocalPose.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_struct_pb2 as base__struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19localpose/LocalPose.proto\x1a\x11\x62\x61se_struct.proto\"\x9c\x01\n\x0eGlobalPoseInfo\x12\x12\n\ntime_stamp\x18\x01 \x01(\x04\x12\x18\n\nworld_pose\x18\x02 \x01(\x0b\x32\x04.Wgs\x12\"\n\x0forientation_cov\x18\x03 \x01(\x0b\x32\t.Vector6d\x12\r\n\x05speed\x18\x04 \x01(\x04\x12\x11\n\tspeed_cov\x18\x05 \x01(\x04\x12\x16\n\x0eloc_acc_status\x18\x06 \x01(\r\"3\n\x10LocalPoseCovInfo\x12\x1f\n\x0cposition_cov\x18\x01 \x01(\x0b\x32\t.Vector6d\"w\n\x10LocalPoseInfoMsg\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12$\n\x0bglobal_pose\x18\x02 \x01(\x0b\x32\x0f.GlobalPoseInfo\x12*\n\x0fsmooth_pose_cov\x18\x03 \x01(\x0b\x32\x11.LocalPoseCovInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'localpose.LocalPose_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GLOBALPOSEINFO']._serialized_start=49
  _globals['_GLOBALPOSEINFO']._serialized_end=205
  _globals['_LOCALPOSECOVINFO']._serialized_start=207
  _globals['_LOCALPOSECOVINFO']._serialized_end=258
  _globals['_LOCALPOSEINFOMSG']._serialized_start=260
  _globals['_LOCALPOSEINFOMSG']._serialized_end=379
# @@protoc_insertion_point(module_scope)
