# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sr_service/proto/sr2_0/mp_output/mp_output.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sr_service.proto.sr2_0 import base_struct_pb2 as sr__service_dot_proto_dot_sr2__0_dot_base__struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0sr_service/proto/sr2_0/mp_output/mp_output.proto\x12\x12xpilot.sr2_0.proto\x1a(sr_service/proto/sr2_0/base_struct.proto\"\xd9\x01\n\x0bMpOutputMsg\x12\x36\n\x06points\x18\x01 \x03(\x0b\x32&.xpilot.sr2_0.proto.TrajectoryPointMsg\x12\x34\n\x08\x62oudarys\x18\x02 \x03(\x0b\x32\".xpilot.sr2_0.proto.BoundaryObject\x12\x18\n\x10trajectory_color\x18\x03 \x01(\r\x12\x42\n\x12vehicle_stop_point\x18\x04 \x01(\x0b\x32&.xpilot.sr2_0.proto.TrajectoryPointMsgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sr_service.proto.sr2_0.mp_output.mp_output_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MPOUTPUTMSG']._serialized_start=115
  _globals['_MPOUTPUTMSG']._serialized_end=332
# @@protoc_insertion_point(module_scope)
