# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mp_output/mp_output.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_struct_pb2 as base__struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19mp_output/mp_output.proto\x1a\x11\x62\x61se_struct.proto\"\xa0\x01\n\x0bMpOutputMsg\x12#\n\x06points\x18\x01 \x03(\x0b\x32\x13.TrajectoryPointMsg\x12!\n\x08\x62oudarys\x18\x02 \x03(\x0b\x32\x0f.BoundaryObject\x12\x18\n\x10trajectory_color\x18\x03 \x01(\r\x12/\n\x12vehicle_stop_point\x18\x04 \x01(\x0b\x32\x13.TrajectoryPointMsgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mp_output.mp_output_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MPOUTPUTMSG']._serialized_start=49
  _globals['_MPOUTPUTMSG']._serialized_end=209
# @@protoc_insertion_point(module_scope)
