# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_fusion/mf_lanes_for_scu.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_struct_pb2 as base__struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!map_fusion/mf_lanes_for_scu.proto\x1a\x11\x62\x61se_struct.proto\"\xfb\x02\n\x14LaneLineInfo_XPU2SCU\x12\x0e\n\x06LaneID\x18\x01 \x01(\r\x12\x13\n\x0bLaneStartDx\x18\x02 \x01(\x02\x12\x16\n\x0eLaneStartDxStd\x18\x03 \x01(\x02\x12\x11\n\tLaneEndDx\x18\x04 \x01(\x02\x12\x14\n\x0cLaneEndDxStd\x18\x05 \x01(\x02\x12\x15\n\rLaneExistProb\x18\x06 \x01(\r\x12\x10\n\x08LaneType\x18\x07 \x01(\r\x12\x14\n\x0cLaneTypeProb\x18\x08 \x01(\r\x12!\n\tLaneColor\x18\t \x01(\x0e\x32\x0e.LaneLineColor\x12\x14\n\x0cLaneDistY_C0\x18\n \x01(\x02\x12\x17\n\x0fLaneYawAngle_C1\x18\x0b \x01(\x02\x12\x14\n\x0cLaneCurve_C2\x18\x0c \x01(\x02\x12\x1a\n\x12LaneCurveChange_C3\x18\r \x01(\x02\x12\x11\n\tLaneWidth\x18\x0e \x01(\x02\x12\'\n\x0e\x62oudary_object\x18\x0f \x01(\x0b\x32\x0f.BoundaryObject\"\xef\x01\n\x15LaneInfo_List_XPU2SCU\x12\"\n\x03le1\x18\x01 \x01(\x0b\x32\x15.LaneLineInfo_XPU2SCU\x12\"\n\x03ri1\x18\x02 \x01(\x0b\x32\x15.LaneLineInfo_XPU2SCU\x12\"\n\x03le2\x18\x03 \x01(\x0b\x32\x15.LaneLineInfo_XPU2SCU\x12\"\n\x03ri2\x18\x04 \x01(\x0b\x32\x15.LaneLineInfo_XPU2SCU\x12\"\n\x03le3\x18\x05 \x01(\x0b\x32\x15.LaneLineInfo_XPU2SCU\x12\"\n\x03ri3\x18\x06 \x01(\x0b\x32\x15.LaneLineInfo_XPU2SCU\"Z\n\x17MapFusionLanesForScuMsg\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12,\n\x0cxpu_laneinfo\x18\x02 \x01(\x0b\x32\x16.LaneInfo_List_XPU2SCU*\xbb\x01\n\rLaneLineColor\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05WHITE\x10\x01\x12\n\n\x06YELLOW\x10\x02\x12\n\n\x06ORANGE\x10\x03\x12\x08\n\x04\x42LUE\x10\x04\x12\t\n\x05GREEN\x10\x05\x12\x08\n\x04GRAY\x10\x06\x12\x1a\n\x16LEFT_GRAY_RIGHT_YELLOW\x10\x07\x12\x1b\n\x17LEFT_YELLOW_RIGHT_WHITE\x10\x08\x12\t\n\x05\x42LACK\x10\t\x12\n\n\x06OTHERS\x10\n\x12\x0b\n\x07MAX_NUM\x10\x0b\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_fusion.mf_lanes_for_scu_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LANELINECOLOR']._serialized_start=773
  _globals['_LANELINECOLOR']._serialized_end=960
  _globals['_LANELINEINFO_XPU2SCU']._serialized_start=57
  _globals['_LANELINEINFO_XPU2SCU']._serialized_end=436
  _globals['_LANEINFO_LIST_XPU2SCU']._serialized_start=439
  _globals['_LANEINFO_LIST_XPU2SCU']._serialized_end=678
  _globals['_MAPFUSIONLANESFORSCUMSG']._serialized_start=680
  _globals['_MAPFUSIONLANESFORSCUMSG']._serialized_end=770
# @@protoc_insertion_point(module_scope)
