# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state_manage/state_manage.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fstate_manage/state_manage.proto\"\x83\x04\n\x12StateManagementMsg\x12 \n\x18rdmodulecom_CruiseVehSpd\x18\x01 \x01(\x05\x12#\n\x1brdmodulecom_cruisevehSpd_st\x18\x02 \x01(\x02\x12\x18\n\x10rdmodulecom_9_st\x18\x03 \x01(\x05\x12\x1c\n\x14rdmodulecom_10_state\x18\x04 \x01(\x05\x12\x1c\n\x14rdmodulecom_11_state\x18\x05 \x01(\x05\x12\x1c\n\x14rdmodulecom_13_state\x18\x06 \x01(\x05\x12\x1c\n\x14rdmodulecom_14_state\x18\x07 \x01(\x05\x12\x1c\n\x14rdmodulecom_15_state\x18\x08 \x01(\x05\x12\x1c\n\x14rdmodulecom_16_state\x18\t \x01(\x05\x12\x1c\n\x14rdmodulecom_26_state\x18\n \x01(\x05\x12\x1c\n\x14rdmodulecom_29_state\x18\x0b \x01(\x05\x12\x1c\n\x14rdmodulecom_30_state\x18\x0c \x01(\x05\x12\x1c\n\x14rdmodulecom_36_state\x18\r \x01(\x05\x12\x11\n\tmfl_state\x18\x0e \x01(\x05\x12\x1d\n\x15rdmodulecom_turnstate\x18\x0f \x01(\x05\x12\x12\n\nmodel_mode\x18\x10 \x01(\x05\x12\x1a\n\x12intersection_state\x18\x11 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_manage.state_manage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATEMANAGEMENTMSG']._serialized_start=36
  _globals['_STATEMANAGEMENTMSG']._serialized_end=551
# @@protoc_insertion_point(module_scope)
