# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sr_service/proto/sr2_0/mf_localpose/MfLocalPose.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sr_service.proto.sr2_0 import base_struct_pb2 as sr__service_dot_proto_dot_sr2__0_dot_base__struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5sr_service/proto/sr2_0/mf_localpose/MfLocalPose.proto\x12\x12xpilot.sr2_0.proto\x1a(sr_service/proto/sr2_0/base_struct.proto\"\xb9\x02\n\x0eMfLocalPoseMsg\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x38\n\rmf_local_pose\x18\x02 \x01(\x0b\x32!.xpilot.sr2_0.proto.LocalPoseInfo\x12=\n\x17local_frame_ref_in_ecef\x18\x03 \x01(\x0b\x32\x1c.xpilot.sr2_0.proto.Pose6DOF\x12\x14\n\x0clast_mf_time\x18\x04 \x01(\x04\x12\x15\n\rfusion_status\x18\x05 \x01(\r\x12\x36\n\x0bmf_dop_pose\x18\x06 \x01(\x0b\x32!.xpilot.sr2_0.proto.LocalPoseInfo\x12\x36\n\x0bmf_dom_pose\x18\x07 \x01(\x0b\x32!.xpilot.sr2_0.proto.LocalPoseInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sr_service.proto.sr2_0.mf_localpose.MfLocalPose_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MFLOCALPOSEMSG']._serialized_start=120
  _globals['_MFLOCALPOSEMSG']._serialized_end=433
# @@protoc_insertion_point(module_scope)
